version: '3'
services:
  db:
    restart: always
    image: mysql:5.7
    volumes:
      - ./dbdump:/var/lib/mysql
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "develop"
    ports:
      - "3306:3306"
